name: OpenDingux_buildroot

on:
  workflow_dispatch:
   
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/opendingux/retro-toolchain/buildroot
      
    strategy:
      matrix:
        target: [ 'gcw0' ]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Blocked invisible-mirror.net workaround
      run: echo "1.1.1.1 invisible-mirror.net" | tee -a /etc/hosts
    - name: Check disk space
      run: df -h /
    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v4
      with:
        path: dl
        key: downloads
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        file(APPEND $ENV{GITHUB_OUTPUT} "timestamp=${current_date}\n")
    - name: ccache cache files
      uses: actions/cache@v4
      with:
        path: output/ccache/${{ matrix.target }}
        key: ${{ matrix.config.name }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ matrix.config.name }}-ccache-
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: false
        swap-storage: false
    - name: build
      run:
        df -h /
        ./rebuild.sh
      env:
        CONFIG: ${{ matrix.target }}
        TOP_MAKE_COMMAND: utils/brmake
        BR2_JLEVEL: 0
        FORCE_UNSAFE_CONFIGURE: 1
    - uses: actions/upload-artifact@v4
      with:
        name: toolchain-${{ matrix.target }}
        path: |
          output/${{ matrix.target }}/images/*.tar*
    - uses: actions/upload-artifact@v4
      with:
        name: update-${{ matrix.target }}
        path: |
          output/${{ matrix.target }}/images/*.opk
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.target }}-log
        path: |
          br.log


